# Generated by Django 5.1.7 on 2025-03-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('tamanho', models.CharField(blank=True, choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
                ('valor_por_peca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dados_bancarios', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quantidade_em_estoque', models.IntegerField(default=0)),
            ],
        ),
    ]
