# Generated by Django 5.1.7 on 2025-03-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='localizacao',
            new_name='endereco',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='valor_por_peca',
        ),
        migrations.AddField(
            model_name='profissional',
            name='categoria',
            field=models.CharField(choices=[('FACCIONISTA', 'FACCIONISTA'), ('EMBALADEIRA', 'EMBALADEIRA')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
