# Generated by Django 5.1.7 on 2025-03-20 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_mesa', models.CharField(max_length=100)),
                ('data_corte', models.DateTimeField()),
                ('quantidade_cortada', models.IntegerField()),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='cadastro.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_inicial', models.IntegerField()),
                ('quantidade_conferida', models.IntegerField(blank=True, null=True)),
                ('diferenca', models.IntegerField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Criado', max_length=50)),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pedidos.corte')),
            ],
        ),
        migrations.CreateModel(
            name='Embalagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_embalada', models.IntegerField()),
                ('valor_por_peca_embalagem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total_embalagem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embalagens', to='cadastro.profissional')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embalagens', to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Confecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_confeccionada', models.IntegerField()),
                ('valor_por_peca_confecao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total_confecao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confecoes', to='cadastro.profissional')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confecoes', to='pedidos.pedido')),
            ],
        ),
    ]
