# Generated by Django 5.1.7 on 2025-03-20 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_produto'),
        ('pedidos', '0002_remove_confecao_quantidade_confeccionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.produto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='quantidade_utilizada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
